laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('empresa/{slug?}', ['as' => 'empresa', 'uses' => 'EmpresaController@index']);

Route::get('mao-de-obra/{slug?}/{interna?}', ['as' => 'mao-de-obra', 'uses' => 'MaoDeObraController@index']);

Route::get('cases/{id?}', ['as' => 'cases', 'uses' => 'CasesController@index']);

Route::get('vagas', ['as' => 'vagas', 'uses' => 'VagasController@index']);
Route::post('vagas', ['as' => 'vagas.envio', 'uses' => 'VagasController@envio']);

Route::get('imprensa/filtro/{categoria_id}', ['as' => 'imprensa.filtro', 'uses' => 'ImprensaController@filtro']);
Route::get('imprensa/{slug?}', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);

Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Download CV

Route::get('download/{key}', ['as' => 'download', function($key){
    $curriculo = Curriculo::download($key)->first();
    if (!$curriculo) App::abort('404');

    return Response::download(base_path('curriculos/'.$curriculo->curriculo));
}]);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('abrangencia/unidades', 'Painel\UnidadesController');
    Route::resource('abrangencia', 'Painel\AbrangenciaController');

    Route::resource('cases', 'Painel\CasesController');

    Route::resource('curriculos', 'Painel\CurriculosController');

    Route::resource('imprensa/categorias', 'Painel\ImprensaCategoriasController');
    Route::resource('imprensa', 'Painel\ImprensaController');
    Route::resource('imprensa.imagens', 'Painel\ImprensaImagensController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
});

laravel/app/controllers/painel/AbrangenciaController.php
<?php

namespace Painel;

use \Abrangencia, \Input, \Validator, \Redirect, \Session;

class AbrangenciaController extends BasePainelController {

    private $validation_rules = [
        'matriz'             => 'required',
        'matrizes_regionais' => 'required'
    ];

    public function index()
    {
        $matrizes = Abrangencia::first();

        return $this->view('painel.abrangencia.matriz.index', compact('matrizes'));
    }

    public function update($id)
    {
        $matrizes = Abrangencia::findOrFail($id);
        $input    = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $matrizes->update($input);
            Session::flash('sucesso', 'Informações alteradas com sucesso.');

            return Redirect::route('painel.abrangencia.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/CasesController.php
<?php

namespace Painel;

use \Cases, \Input, \Validator, \Redirect, \Session, \CropImage;

class CasesController extends BasePainelController {

    private $validation_rules = [
        'titulo' => 'required',
        'olho'   => 'required',
        'texto'  => 'required',
        'imagem' => 'image'
    ];

    private $image_config = [
        'width'  => 200,
        'height' => 160,
        'path'   => 'assets/img/cases/'
    ];

    public function index()
    {
        $cases = Cases::ordenados()->get();

        return $this->view('painel.cases.index', compact('cases'));
    }

    public function create()
    {
        return $this->view('painel.cases.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Cases::create($input);
            Session::flash('sucesso', 'Case adicionado com sucesso.');

            return Redirect::route('painel.cases.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar case.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $case = Cases::findOrFail($id);

        return $this->view('painel.cases.edit', compact('case'));
    }

    public function update($id)
    {
        $case = Cases::findOrFail($id);
        $input  = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            if (Input::has('remover_imagem')) {
                $input['imagem'] = null;
                unset($input['remover_imagem']);
            }

            $case->update($input);
            Session::flash('sucesso', 'Case alterado com sucesso.');

            return Redirect::route('painel.cases.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar case.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Cases::destroy($id);
            Session::flash('sucesso', 'Case removido com sucesso.');

            return Redirect::route('painel.cases.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover case.']);

        }
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email' => 'required|email'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(10);

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/CurriculosController.php
<?php

namespace Painel;

use \Curriculo, \Session, \Redirect;

class CurriculosController extends BasePainelController {

    public function index()
    {
        $curriculos = Curriculo::orderBy('id', 'DESC')->paginate(10);

        return $this->view('painel.curriculos.index', compact('curriculos'));
    }

    public function show($id)
    {
        $curriculo = Curriculo::findOrFail($id);

        return $this->view('painel.curriculos.show', compact('curriculo'));
    }

    public function destroy($id)
    {
        try {

            Curriculo::destroy($id);
            Session::flash('sucesso', 'Currículo removido com sucesso.');

            return Redirect::route('painel.curriculos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover currículo.']);

        }
    }

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use \View, \Input, \Auth, \Session, \Redirect;

class HomeController extends BasePainelController {

    public function index()
    {
        return $this->view('painel.home');
    }

    public function login()
    {
        return $this->view('painel.login');
    }

    public function attempt()
    {
        $authvars = array(
            'username' => Input::get('username'),
            'password' => Input::get('password')
        );

        $lembrar = (Input::get('lembrar') == 'true') ? true : false;

        if (Auth::attempt($authvars, $lembrar)) {
            return Redirect::route('painel.home');
        } else {
            Session::flash('login_errors', true);
            return Redirect::route('painel.login')->withInput(Input::except('password'));
        }
    }

    public function logout()
    {
        Auth::logout();
        return Redirect::route('home');
    }

}

laravel/app/controllers/painel/ImprensaCategoriasController.php
<?php

namespace Painel;

use \ImprensaCategoria, \Input, \Validator, \Redirect, \Session;

class ImprensaCategoriasController extends BasePainelController {

    private $validation_rules = [
        'categoria' => 'required',
    ];

    public function index()
    {
        $categorias = ImprensaCategoria::get();

        return $this->view('painel.imprensacategorias.index', compact('categorias'));
    }

    public function create()
    {
        return $this->view('painel.imprensacategorias.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            ImprensaCategoria::create($input);
            Session::flash('sucesso', 'Categoria adicionada com sucesso.');

            return Redirect::route('painel.imprensa.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao adicionar categoria.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $categoria = ImprensaCategoria::findOrFail($id);

        return $this->view('painel.imprensacategorias.edit', compact('categoria'));
    }

    public function update($id)
    {
        $categoria = ImprensaCategoria::findOrFail($id);
        $input     = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $categoria->update($input);
            Session::flash('sucesso', 'Categoria alterada com sucesso.');

            return Redirect::route('painel.imprensa.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar categoria.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            ImprensaCategoria::destroy($id);
            Session::flash('sucesso', 'Categoria removida com sucesso.');

            return Redirect::route('painel.imprensa.categorias.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover categoria.']);

        }
    }

}

laravel/app/controllers/painel/ImprensaImagensController.php
<?php

namespace Painel;

use \Imprensa, \ImprensaImagem, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ImprensaImagensController extends BasePainelController {

    private $validation_rules = [
        'imagem'   => 'required|image'
    ];

    private $image_config = [
        'width'  => 560,
        'height' => 420,
        'path'   => 'assets/img/imprensa/'
    ];

    public function index($imprensa_id)
    {
        $imprensa = Imprensa::find($imprensa_id);
        if(!$imprensa) return Redirect::route('painel.imprensa.index');

        $imagens = ImprensaImagem::imprensa($imprensa_id)->ordenados()->get();

        return $this->view('painel.imprensaimagens.index', compact('imprensa', 'imagens'));
    }

    public function create($imprensa_id)
    {
        $imprensa = Imprensa::find($imprensa_id);
        if(!$imprensa) return Redirect::route('painel.imprensa.index');

        return $this->view('painel.imprensaimagens.create', compact('imprensa'));
    }

    public function store($imprensa_id)
    {
        $input = Input::all();
        $input['imprensa_id'] = $imprensa_id;

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            ImprensaImagem::create($input);
            Session::flash('sucesso', 'Imagem inserida com sucesso.');

            return Redirect::route('painel.imprensa.imagens.index', $input['imprensa_id']);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao inserir imagem.'])
                ->withInput();

        }
    }

    public function destroy($imprensa_id, $imagem_id)
    {
        try {

            ImprensaImagem::destroy($imagem_id);
            Session::flash('sucesso', 'Imagem removida com sucesso.');

            return Redirect::route('painel.imprensa.imagens.index', $imprensa_id);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover imagem.']);

        }
    }

}

laravel/app/views/painel/common/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url() }}">{{ Config::get('projeto.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown @if(str_is('painel.abrangencia*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Abrangência <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.abrangencia.index') }}">Matrizes</a></li>
                        <li><a href="{{ route('painel.abrangencia.unidades.index') }}">Unidades Generalistas</a></li>
                    </ul>
                </li>

                <li @if(str_is('painel.cases*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.cases.index') }}">Cases</a>
                </li>

                <li @if(str_is('painel.curriculos*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.curriculos.index') }}">Currículos</a>
                </li>

                <li @if(str_is('painel.imprensa*', Route::currentRouteName())) class="active" @endif>
                    <a href="{{ route('painel.imprensa.index') }}">Imprensa</a>
                </li>

                <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contato @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
                        <li><a href="{{ route('painel.contato.recebidos.index') }}">Contatos Recebidos @if($recebidos_count>=1)<span class="badge">{{ $recebidos_count }}</span>@endif</a></li>
                    </ul>
                </li>

                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                        <li><a href="{{ route('painel.logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/app/views/painel/common/template.blade.php
<?php $login = (Route::currentRouteName() == 'painel.login'); ?>
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ Config::get('projeto.name') }} - Painel Administrativo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel/painel.min.css') }}">
    <script>var BASE = '{{ url() }}'</script>
</head>
<body class="{{ ($login ? 'login' : 'painel') }}">
    @if(!$login)
        @include('painel.common.nav')
    @endif

    <div class="{{ ($login ? 'wrapper' : 'main container') }}">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="assets/js/jquery.min.js"><\/script>')</script>
    <script src="{{ asset('assets/js/painel/vendor.min.js') }}"></script>
    <script src="{{ asset('assets/js/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/painel/painel.js?1') }}"></script>
</body>
</html>